In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
bnb_df = pd.read_csv(Path('../resources/coin_BinanceCoin.csv'), index_col='SNo')
bnb_df

,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
SNo,,,,,,,,,
1,Binance Coin,BNB,2017-07-26 23:59:59,0.109013,0.099266,0.105893,0.105138,2.003950e+05,1.051380e+07
2,Binance Coin,BNB,2017-07-27 23:59:59,0.108479,0.100888,0.105108,0.107737,3.444990e+05,1.077370e+07
3,Binance Coin,BNB,2017-07-28 23:59:59,0.109019,0.101473,0.107632,0.104067,3.425680e+05,1.040670e+07
4,Binance Coin,BNB,2017-07-29 23:59:59,0.111264,0.101108,0.104782,0.107811,3.402180e+05,1.078110e+07
5,Binance Coin,BNB,2017-07-30 23:59:59,0.108138,0.103162,0.107935,0.106414,2.242610e+05,1.064140e+07
...,...,...,...,...,...,...,...,...,...
1309,Binance Coin,BNB,2021-02-23 23:59:59,268.536845,190.412463,267.364425,230.994252,8.280753e+09,3.569619e+10
1310,Binance Coin,BNB,2021-02-24 23:59:59,280.088196,214.524714,231.121604,254.359132,7.154122e+09,3.930683e+10
1311,Binance Coin,BNB,2021-02-25 23:59:59,264.705134,233.885956,254.467606,233.885956,4.059853e+09,3.614305e+10
1312,Binance Coin,BNB,2021-02-26 23:59:59,238.755012,210.310761,235.270287,221.680429,4.167146e+09,3.425689e+10
1313,Binance Coin,BNB,2021-02-27 23:59:59,237.179435,220.099401,221.980905,225.249443,2.755271e+09,3.480842e+10

In [3]:
bnb_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1313 entries, 1 to 1313
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       1313 non-null   object
 1   Symbol     1313 non-null   object
 2   Date       1313 non-null   object
 3   High       1313 non-null   float64
 4   Low        1313 non-null   float64
 5   Open       1313 non-null   float64
 6   Close      1313 non-null   float64
 7   Volume     1313 non-null   float64
 8   Marketcap  1313 non-null   float64
dtypes: float64(6), object(3)
memory usage: 102.6+ KB

In [4]:
bnb_df['Date'] = pd.to_datetime(bnb_df['Date'])
bnb_df.dtypes

Name                 object
Symbol               object
Date         datetime64[ns]
High                float64
Low                 float64
Open                float64
Close               float64
Volume              float64
Marketcap           float64
dtype: object