In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
ltc_df = pd.read_csv(Path('../resources/coin_Litecoin.csv'), index_col='SNo')
ltc_df

,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
SNo,,,,,,,,,
1,Litecoin,LTC,2013-04-29 23:59:59,4.573600,4.225640,4.366760,4.383900,0.000000e+00,7.538896e+07
2,Litecoin,LTC,2013-04-30 23:59:59,4.572380,4.168960,4.403520,4.296490,0.000000e+00,7.402092e+07
3,Litecoin,LTC,2013-05-01 23:59:59,4.356860,3.520290,4.289540,3.801010,0.000000e+00,6.560460e+07
4,Litecoin,LTC,2013-05-02 23:59:59,4.039300,3.007170,3.780020,3.371980,0.000000e+00,5.828798e+07
5,Litecoin,LTC,2013-05-03 23:59:59,3.453610,2.395940,3.390440,3.044910,0.000000e+00,5.269485e+07
...,...,...,...,...,...,...,...,...,...
2858,Litecoin,LTC,2021-02-23 23:59:59,208.369670,159.684673,208.123407,176.934915,1.094470e+10,1.177356e+10
2859,Litecoin,LTC,2021-02-24 23:59:59,189.165459,169.789009,176.966769,181.378501,7.205360e+09,1.207051e+10
2860,Litecoin,LTC,2021-02-25 23:59:59,204.743842,176.032145,181.385422,178.901843,7.327999e+09,1.190489e+10
2861,Litecoin,LTC,2021-02-26 23:59:59,182.075844,163.248248,179.128519,170.398153,7.875998e+09,1.134030e+10
2862,Litecoin,LTC,2021-02-27 23:59:59,179.929872,167.908789,170.431423,172.100447,4.991079e+09,1.145486e+10

In [3]:
ltc_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2862 entries, 1 to 2862
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       2862 non-null   object
 1   Symbol     2862 non-null   object
 2   Date       2862 non-null   object
 3   High       2862 non-null   float64
 4   Low        2862 non-null   float64
 5   Open       2862 non-null   float64
 6   Close      2862 non-null   float64
 7   Volume     2862 non-null   float64
 8   Marketcap  2862 non-null   float64
dtypes: float64(6), object(3)
memory usage: 223.6+ KB

In [4]:
ltc_df['Date'] = pd.to_datetime(ltc_df['Date'])
ltc_df.dtypes

Name                 object
Symbol               object
Date         datetime64[ns]
High                float64
Low                 float64
Open                float64
Close               float64
Volume              float64
Marketcap           float64
dtype: object