In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# load and inspect data
aave_df = pd.read_csv(Path('../resources/prices/coin_Aave.csv'), index_col='SNo')
aave_df

,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
SNo,,,,,,,,,
1,Aave,AAVE,2020-10-05 23:59:59,55.112358,49.787900,52.675035,53.219243,0.000000e+00,8.912813e+07
2,Aave,AAVE,2020-10-06 23:59:59,53.402270,40.734578,53.291969,42.401599,5.830915e+05,7.101144e+07
3,Aave,AAVE,2020-10-07 23:59:59,42.408314,35.970690,42.399947,40.083976,6.828342e+05,6.713004e+07
4,Aave,AAVE,2020-10-08 23:59:59,44.902511,36.696057,39.885262,43.764463,1.658817e+06,2.202651e+08
5,Aave,AAVE,2020-10-09 23:59:59,47.569533,43.291776,43.764463,46.817744,8.155377e+05,2.356322e+08
...,...,...,...,...,...,...,...,...,...
142,Aave,AAVE,2021-02-23 23:59:59,401.648853,288.714523,400.784976,359.497520,1.179704e+09,4.461395e+09
143,Aave,AAVE,2021-02-24 23:59:59,402.910314,344.938860,360.210985,367.230900,7.635339e+08,4.557747e+09
144,Aave,AAVE,2021-02-25 23:59:59,384.707877,337.501464,367.219217,337.501464,4.506436e+08,4.189245e+09
145,Aave,AAVE,2021-02-26 23:59:59,350.865442,305.153562,338.277176,323.108175,5.491783e+08,4.011296e+09
146,Aave,AAVE,2021-02-27 23:59:59,349.178494,323.376116,323.376116,334.364481,4.002361e+08,4.151559e+09

In [3]:

aave_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 146 entries, 1 to 146
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       146 non-null    object
 1   Symbol     146 non-null    object
 2   Date       146 non-null    object
 3   High       146 non-null    float64
 4   Low        146 non-null    float64
 5   Open       146 non-null    float64
 6   Close      146 non-null    float64
 7   Volume     146 non-null    float64
 8   Marketcap  146 non-null    float64
dtypes: float64(6), object(3)
memory usage: 11.4+ KB

In [4]:
aave_df['Date'] = pd.to_datetime(aave_df['Date']).dt.date
aave_df['Date'] = pd.to_datetime(aave_df['Date'])
aave_df.dtypes

Name                 object
Symbol               object
Date         datetime64[ns]
High                float64
Low                 float64
Open                float64
Close               float64
Volume              float64
Marketcap           float64
dtype: object

In [5]:
aave_df['Spread'] = aave_df.High - aave_df.Low

In [6]:
aave_df

,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap,Spread
SNo,,,,,,,,,,
1,Aave,AAVE,2020-10-05,55.112358,49.787900,52.675035,53.219243,0.000000e+00,8.912813e+07,5.324459
2,Aave,AAVE,2020-10-06,53.402270,40.734578,53.291969,42.401599,5.830915e+05,7.101144e+07,12.667692
3,Aave,AAVE,2020-10-07,42.408314,35.970690,42.399947,40.083976,6.828342e+05,6.713004e+07,6.437624
4,Aave,AAVE,2020-10-08,44.902511,36.696057,39.885262,43.764463,1.658817e+06,2.202651e+08,8.206454
5,Aave,AAVE,2020-10-09,47.569533,43.291776,43.764463,46.817744,8.155377e+05,2.356322e+08,4.277757
...,...,...,...,...,...,...,...,...,...,...
142,Aave,AAVE,2021-02-23,401.648853,288.714523,400.784976,359.497520,1.179704e+09,4.461395e+09,112.934330
143,Aave,AAVE,2021-02-24,402.910314,344.938860,360.210985,367.230900,7.635339e+08,4.557747e+09,57.971453
144,Aave,AAVE,2021-02-25,384.707877,337.501464,367.219217,337.501464,4.506436e+08,4.189245e+09,47.206414
145,Aave,AAVE,2021-02-26,350.865442,305.153562,338.277176,323.108175,5.491783e+08,4.011296e+09,45.711880
146,Aave,AAVE,2021-02-27,349.178494,323.376116,323.376116,334.364481,4.002361e+08,4.151559e+09,25.802377